# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastPDist <- function(Ar, Br) {
    .Call('_SVP_fastPDist', PACKAGE = 'SVP', Ar, Br)
}

MCAStep1 <- function(X) {
    .Call('_SVP_MCAStep1', PACKAGE = 'SVP', X)
}

MCAStep2 <- function(Z, V, Dc) {
    .Call('_SVP_MCAStep2', PACKAGE = 'SVP', Z, V, Dc)
}

parallelCalRWR <- function(x, v, restart = 0.75, stop_delta = 0.000001, stop_step = 2L) {
    .Call('_SVP_parallelCalRWR', PACKAGE = 'SVP', x, v, restart, stop_delta, stop_step)
}

