# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastPDist <- function(Ar, Br) {
    .Call('_SVP_fastPDist', PACKAGE = 'SVP', Ar, Br)
}

MCAStep1 <- function(X) {
    .Call('_SVP_MCAStep1', PACKAGE = 'SVP', X)
}

MCAStep2 <- function(Z, V, Dc) {
    .Call('_SVP_MCAStep2', PACKAGE = 'SVP', Z, V, Dc)
}

calRWRCPP <- function(x, v, restart = .7, delta = 1, step = 0L, stop_delta = 1e-6, stop_step = 50L) {
    .Call('_SVP_calRWRCPP', PACKAGE = 'SVP', x, v, restart, delta, step, stop_delta, stop_step)
}

