# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MatMultCpp <- function(A, B) {
    .Call('_SVP_MatMultCpp', PACKAGE = 'SVP', A, B)
}

SpMatElemMultiMat <- function(x, y) {
    .Call('_SVP_SpMatElemMultiMat', PACKAGE = 'SVP', x, y)
}

SpMatElemMultiSpMat <- function(x, y) {
    .Call('_SVP_SpMatElemMultiSpMat', PACKAGE = 'SVP', x, y)
}

MatElemMultiMat <- function(x, y) {
    .Call('_SVP_MatElemMultiMat', PACKAGE = 'SVP', x, y)
}

corCpp <- function(x, y) {
    .Call('_SVP_corCpp', PACKAGE = 'SVP', x, y)
}

CalParallelCor <- function(x) {
    .Call('_SVP_CalParallelCor', PACKAGE = 'SVP', x)
}

CalParallelBiCor <- function(x) {
    .Call('_SVP_CalParallelBiCor', PACKAGE = 'SVP', x)
}

CalParallelBiCorTwoMatrix <- function(x, y) {
    .Call('_SVP_CalParallelBiCorTwoMatrix', PACKAGE = 'SVP', x, y)
}

ExtractFeatureScoreCpp <- function(x, rnm, cnm, g) {
    .Call('_SVP_ExtractFeatureScoreCpp', PACKAGE = 'SVP', x, rnm, cnm, g)
}

CalGearyscParallel <- function(x, weight, permutation = 999L) {
    .Call('_SVP_CalGearyscParallel', PACKAGE = 'SVP', x, weight, permutation)
}

findIntervalCpp <- function(x, breaks) {
    .Call('_SVP_findIntervalCpp', PACKAGE = 'SVP', x, breaks)
}

outergrid <- function(grid, x) {
    .Call('_SVP_outergrid', PACKAGE = 'SVP', grid, x)
}

CalRandSpatialKld <- function(w, bg, axm, aym, h, indx, indy, random_times = 100L, seed = 1024.0) {
    .Call('_SVP_CalRandSpatialKld', PACKAGE = 'SVP', w, bg, axm, aym, h, indx, indy, random_times, seed)
}

CalBgSpatialKld <- function(coords, axm, aym, h, indx, indy) {
    .Call('_SVP_CalBgSpatialKld', PACKAGE = 'SVP', coords, axm, aym, h, indx, indy)
}

CalSpatialKld <- function(d, bgkld, axm, aym, h, indx, indy, random_times = 100L, seed = 1024.0) {
    .Call('_SVP_CalSpatialKld', PACKAGE = 'SVP', d, bgkld, axm, aym, h, indx, indy, random_times, seed)
}

CalWkdeParallel <- function(x, w, l, h, adjust = 1.0, n = 400L) {
    .Call('_SVP_CalWkdeParallel', PACKAGE = 'SVP', x, w, l, h, adjust, n)
}

MCAStep1 <- function(X) {
    .Call('_SVP_MCAStep1', PACKAGE = 'SVP', X)
}

MCAStep2 <- function(Z, V, Dc) {
    .Call('_SVP_MCAStep2', PACKAGE = 'SVP', Z, V, Dc)
}

CalMoransiParallel <- function(x, weight, scaled = FALSE, permutation = 999L) {
    .Call('_SVP_CalMoransiParallel', PACKAGE = 'SVP', x, weight, scaled, permutation)
}

fastPDist <- function(A, B) {
    .Call('_SVP_fastPDist', PACKAGE = 'SVP', A, B)
}

fusiondist <- function(s, p, alpha = 0.2, beta = 0.1) {
    .Call('_SVP_fusiondist', PACKAGE = 'SVP', s, p, alpha, beta)
}

ParallelColOrder <- function(x, top_n) {
    .Call('_SVP_ParallelColOrder', PACKAGE = 'SVP', x, top_n)
}

parallelCalRWR <- function(x, v, restart = 0.75, stop_delta = 1e-10, stop_step = 50L) {
    .Call('_SVP_parallelCalRWR', PACKAGE = 'SVP', x, v, restart, stop_delta, stop_step)
}

